version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATA_DIR=/data
      - FRONTEND_ORIGIN=http://localhost:3001
    volumes:
      - ./data:/data:ro
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./data:/data:ro
    ports:
      - "3001:3000"
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0"
